using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.Administration.Logs;
using Content.Shared.Database;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;


namespace Content.Client.Clown;

[GenerateTypedNameReferences]
public sealed partial class ClownNameMenu : DefaultWindow
{
    public event Action<BaseButton.ButtonEventArgs,string>? OnSendButtonPressed;



    public ClownNameMenu(string name)
    {
        RobustXamlLoader.Load(this);
        OnSendButton.OnButtonDown += args=>{
            OnSendButtonPressed?.Invoke(args,InputName.Text);
            Close();
        };
        OnCancelButton.OnPressed+=_=>Close();
        InputName.OnTextChanged+=args=>{
            if(args.Text=="" ){
                OnSendButton.Disabled=true;
            }
            else{
                OnSendButton.Disabled=false;
            }
        };
    }


    public override void Close()
    {
        base.Close();

    }
}
